name: labeeb_front
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  #UI
  flutter_native_splash: ^2.1.0
  flutter_svg: ^1.0.3
  easy_localization: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  expandable: ^5.0.1
  group_radio_button: ^1.2.0
  flutter_zoom_drawer: ^3.0.3
  font_awesome_flutter: ^10.1.0
  date_time_picker: ^2.1.0
  lottie: ^1.4.1
  #maps
  google_maps_flutter: ^2.1.10
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  custom_marker: ^1.0.0
  toggle_switch: ^2.0.1
  geocoder:
    git:
      https://github.com/aloisdeniel/flutter_geocoder.git
  #state management
  flutter_bloc: ^8.0.1
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/json/
    - assets/lottie/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

